name: crypto_ui_web
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CH
      fonts:
        - asset: assets/fonts/ClashDisplay-Bold.ttf
          weight: 900
        - asset: assets/fonts/ClashDisplay-Extralight.ttf
          weight: 200
        - asset: assets/fonts/ClashDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/ClashDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/ClashDisplay-Semibold.ttf
          weight: 600
          style: italic
